const countries = [
  { label: 'Argentina', code: 'AR' },
  { label: 'Bolivia', code: 'BO' },
  { label: 'Brasil', code: 'BR' },
  { label: 'Chile', code: 'CL' },
  { label: 'Colombia', code: 'CO' },
  { label: 'Costa Rica', code: 'CR' },
  { label: 'Cuba', code: 'CU' },
  { label: 'República Dominicana', code: 'DO' },
  { label: 'Ecuador', code: 'EC' },
  { label: 'El Salvador', code: 'SV' },
  { label: 'Guatemala', code: 'GT' },
  { label: 'Haití', code: 'HT' },
  { label: 'Honduras', code: 'HN' },
  { label: 'México', code: 'MX' },
  { label: 'Nicaragua', code: 'NI' },
  { label: 'Panamá', code: 'PA' },
  { label: 'Paraguay', code: 'PY' },
  { label: 'Perú', code: 'PE' },
  { label: 'Puerto Rico', code: 'PR' },
  { label: 'Uruguay', code: 'UY' },
  { label: 'Venezuela', code: 'VE' },
  { label: 'Belice', code: 'BZ' },
  { label: 'Guyana', code: 'GY' },
  { label: 'Surinam', code: 'SR' },
  { label: 'Trinidad y Tobago', code: 'TT' },
];

export default countries;
